/**
 * Mock data for Vibelearn frontend
 * Grounded in docs/seed.ndjson and docs/videos.json
 */

export const MOCK_COURSES = [
  {
    id: "course-1",
    title: "Next.js for Production",
    slug: "nextjs-for-production",
    summary:
      "Build scalable, high-performance web applications with Next.js, best practices, and production-ready deployment strategies.",
    level: "Intermediate",
    duration: "18h 24m",
    totalModules: 12,
    studentsCount: "2.1k students",
    badge: "Popular",
    badgeVariant: "popular",
    homeBadge: "Beginner",
    iconText: "N",
    iconBg: "bg-black text-white",
    coverImageUrl:
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80",
    instructor: {
      name: "Mira Kovac",
      role: "Principal Frontend Architect",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80",
    },
    whatYouLearn: [
      {
        id: "wyl-1",
        title: "App Router Foundations",
        description: "Master the App Router, layouts, loading states, and nested routing.",
        icon: "Layers",
      },
      {
        id: "wyl-2",
        title: "Data Fetching & Caching",
        description: "Fetch data efficiently and leverage caching for better performance.",
        icon: "Database",
      },
      {
        id: "wyl-3",
        title: "Performance Optimization",
        description: "Optimize rendering, assets, and bundle size for faster apps.",
        icon: "Gauge",
      },
      {
        id: "wyl-4",
        title: "Deployment & Scaling",
        description: "Deploy with confidence and scale your Next.js applications.",
        icon: "Cloud",
      },
    ],
    modules: [
      {
        id: "mod-1",
        order: 1,
        title: "Introduction to Next.js",
        subtitle: "Understand the core features of Next.js and why it's the React framework.",
        duration: "45m",
        lessons: [
          {
            id: "les-1-1",
            title: "What is Next.js & App Router",
            slug: "what-is-nextjs",
            duration: "12:45",
            youtubeVideoId: "9602Yzvd7ik",
            type: "video",
          },
          {
            id: "les-1-2",
            title: "Project Architecture & Directory Structure",
            slug: "project-architecture",
            duration: "15:20",
            youtubeVideoId: "k48WMdl2eUc",
            type: "video",
          },
          {
            id: "les-1-3",
            title: "Client-Side vs Server-Side Trade-offs",
            slug: "rendering-tradeoffs",
            duration: "16:55",
            youtubeVideoId: "rGPpQdbDbwo",
            type: "lesson",
          },
        ],
      },
      {
        id: "mod-2",
        order: 2,
        title: "Project Setup & Structure",
        subtitle: "Set up a new Next.js project and explore the folder structure.",
        duration: "1h 12m",
        lessons: [
          {
            id: "les-2-1",
            title: "File-System Routing Deep Dive",
            slug: "file-system-routing",
            duration: "24:10",
            youtubeVideoId: "9602Yzvd7ik",
            type: "video",
          },
          {
            id: "les-2-2",
            title: "Dynamic Route Segments & Params",
            slug: "dynamic-routes",
            duration: "22:30",
            youtubeVideoId: "j3QJ1Rhxxbw",
            type: "video",
          },
          {
            id: "les-2-3",
            title: "Catch-All & Optional Catch-All Routes",
            slug: "catch-all-routes",
            duration: "25:20",
            youtubeVideoId: "k48WMdl2eUc",
            type: "lesson",
          },
        ],
      },
      {
        id: "mod-3",
        order: 3,
        title: "Routing & Layouts",
        subtitle: "Learn about file-based routing, layouts, and nested routes.",
        duration: "1h 36m",
        lessons: [
          {
            id: "les-3-1",
            title: "Root & Nested Layouts Hierarchy",
            slug: "nested-layouts",
            duration: "28:15",
            youtubeVideoId: "k48WMdl2eUc",
            type: "video",
          },
          {
            id: "les-3-2",
            title: "Templates vs Layouts: Re-mounting",
            slug: "templates-vs-layouts",
            duration: "32:00",
            youtubeVideoId: "k48WMdl2eUc",
            type: "video",
          },
          {
            id: "les-3-3",
            title: "Route Groups & Private Folders",
            slug: "route-groups",
            duration: "35:45",
            youtubeVideoId: "j3QJ1Rhxxbw",
            type: "lesson",
          },
        ],
      },
      {
        id: "mod-4",
        order: 4,
        title: "Server Components",
        subtitle: "Build components with server-side rendering and data fetching.",
        duration: "1h 42m",
        lessons: [
          {
            id: "les-4-1",
            title: "React Server Components Architecture",
            slug: "rsc-architecture",
            duration: "34:10",
            youtubeVideoId: "rGPpQdbDbwo",
            type: "video",
          },
          {
            id: "les-4-2",
            title: "The 'use client' Boundary Strategy",
            slug: "use-client-boundary",
            duration: "32:40",
            youtubeVideoId: "Qdkg_mrniLk",
            type: "video",
          },
          {
            id: "les-4-3",
            title: "Passing Props Across the Server Boundary",
            slug: "passing-props-boundary",
            duration: "35:10",
            youtubeVideoId: "dMCSiA5gzkU",
            type: "lesson",
          },
        ],
      },
      {
        id: "mod-5",
        order: 5,
        title: "Data Fetching & Caching",
        subtitle: "Fetch data efficiently and leverage caching for better performance.",
        duration: "1h 28m",
        lessons: [
          {
            id: "les-5-1",
            title: "Data Fetching in Server Components",
            slug: "data-fetching-in-server-components",
            duration: "12:45",
            youtubeVideoId: "WKfPctdIDek",
            type: "video",
            notes: {
              overview:
                "In this lesson, you'll learn how Next.js handles data fetching and caching in both Server and Client Components. We'll explore different caching strategies and revalidation techniques to build fast and scalable applications.",
              codeLab:
                "Open the code lab below to practice what you've learned. Write your code, see instant feedback, and build real features!",
              inThisLesson: [
                "Understand the different data fetching methods in Next.js",
                "Learn how caching works in Server Components",
                "Implement revalidation and cache control",
                "Optimize performance with advanced caching strategies",
              ],
              proTip:
                "Use caching and revalidation wisely to ensure your app stays fast and data remains fresh without unnecessary requests.",
              resources: [
                {
                  title: "Next.js Data Fetching Documentation",
                  desc: "Official Next.js docs on data fetching methods.",
                  url: "https://nextjs.org/docs/app/building-your-application/data-fetching",
                },
                {
                  title: "Caching and Revalidation Guide",
                  desc: "Deep dive into Next.js caching strategies.",
                  url: "https://nextjs.org/docs/app/building-your-application/caching",
                },
                {
                  title: "Example Repository",
                  desc: "Explore the source code for this lesson.",
                  url: "https://github.com",
                },
              ],
            },
          },
          {
            id: "les-5-2",
            title: "Caching Strategies & Revalidation",
            slug: "caching-strategies",
            duration: "23:00",
            youtubeVideoId: "rGPpQdbDbwo",
            type: "video",
          },
          {
            id: "les-5-3",
            title: "Revalidation & Cache Control",
            slug: "revalidation-cache-control",
            duration: "18:00",
            youtubeVideoId: "k48WMdl2eUc",
            type: "video",
          },
          {
            id: "les-5-4",
            title: "Hands-on: Implement Caching",
            slug: "hands-on-caching",
            duration: "26:00",
            youtubeVideoId: "dMCSiA5gzkU",
            type: "lesson",
          },
        ],
      },
      {
        id: "mod-6",
        order: 6,
        title: "Authentication",
        subtitle: "Implement authentication using Clerk in your app.",
        duration: "1h 18m",
        lessons: [
          {
            id: "les-6-1",
            title: "Setting up Clerk in Next.js",
            slug: "setting-up-clerk",
            duration: "22:15",
            youtubeVideoId: "Qdkg_mrniLk",
            type: "video",
          },
          {
            id: "les-6-2",
            title: "Protecting Routes and Server Actions",
            slug: "protecting-routes",
            duration: "26:45",
            youtubeVideoId: "dMCSiA5gzkU",
            type: "video",
          },
        ],
      },
      {
        id: "mod-7",
        order: 7,
        title: "API Routes & Handlers",
        subtitle: "Create backend endpoints with Route Handlers.",
        duration: "1h 26m",
        lessons: [
          {
            id: "les-7-1",
            title: "Route Handlers Anatomy",
            slug: "route-handlers-anatomy",
            duration: "24:00",
            youtubeVideoId: "WKfPctdIDek",
            type: "video",
          },
        ],
      },
      {
        id: "mod-8",
        order: 8,
        title: "Middleware & Edge Functions",
        subtitle: "Intercept requests before routing with Next.js Middleware.",
        duration: "1h 10m",
        lessons: [
          {
            id: "les-8-1",
            title: "Middleware Routing and Rewrites",
            slug: "middleware-routing",
            duration: "20:00",
            youtubeVideoId: "9602Yzvd7ik",
            type: "video",
          },
        ],
      },
      {
        id: "mod-9",
        order: 9,
        title: "Performance Optimization",
        subtitle: "Optimizing bundle size, font loading, and script strategies.",
        duration: "1h 34m",
        lessons: [
          {
            id: "les-9-1",
            title: "Core Web Vitals Optimization",
            slug: "cwv-optimization",
            duration: "30:00",
            youtubeVideoId: "rGPpQdbDbwo",
            type: "video",
          },
        ],
      },
      {
        id: "mod-10",
        order: 10,
        title: "Deployment on Vercel",
        subtitle: "Deploy preview environments and manage environment variables.",
        duration: "56m",
        lessons: [
          {
            id: "les-10-1",
            title: "Vercel Production Deployment",
            slug: "vercel-deployment",
            duration: "25:00",
            youtubeVideoId: "k48WMdl2eUc",
            type: "video",
          },
        ],
      },
      {
        id: "mod-11",
        order: 11,
        title: "Monitoring & Logging",
        subtitle: "Set up telemetry, analytics, and error tracking.",
        duration: "1h 08m",
        lessons: [
          {
            id: "les-11-1",
            title: "OpenTelemetry & Log Drains",
            slug: "opentelemetry-logging",
            duration: "28:00",
            youtubeVideoId: "dMCSiA5gzkU",
            type: "video",
          },
        ],
      },
      {
        id: "mod-12",
        order: 12,
        title: "Best Practices & Next Steps",
        subtitle: "Refactoring patterns, security audit, and enterprise architecture.",
        duration: "52m",
        lessons: [
          {
            id: "les-12-1",
            title: "Architecture Review & Production Checklist",
            slug: "production-checklist",
            duration: "26:00",
            youtubeVideoId: "rGPpQdbDbwo",
            type: "video",
          },
        ],
      },
    ],
  },
  {
    id: "course-2",
    title: "Docker Essentials",
    slug: "docker-essentials",
    summary:
      "Containerize applications and streamline your development workflow with modern Docker tools and best practices.",
    level: "Beginner",
    duration: "10h 12m",
    totalModules: 8,
    studentsCount: "1.8k students",
    badge: "Popular",
    badgeVariant: "popular",
    homeBadge: "Popular",
    iconText: "🐳",
    iconBg: "bg-sky-100 text-sky-600",
    coverImageUrl:
      "https://images.unsplash.com/photo-1605745341112-85968b19335b?w=800&auto=format&fit=crop&q=80",
    instructor: {
      name: "Tomas Berg",
      role: "Infrastructure Engineer",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80",
    },
    whatYouLearn: [
      {
        id: "dwyl-1",
        title: "Container Foundations",
        description: "Understand cgroups, namespaces, and Docker daemon architecture.",
        icon: "Layers",
      },
      {
        id: "dwyl-2",
        title: "Multi-Stage Dockerfiles",
        description: "Write lean, secure production Dockerfiles for Node and Go.",
        icon: "FileCode",
      },
      {
        id: "dwyl-3",
        title: "Docker Compose Mastery",
        description: "Orchestrate local multi-service development stacks with ease.",
        icon: "Boxes",
      },
      {
        id: "dwyl-4",
        title: "Networking & Volumes",
        description: "Manage persistent data, bridge networks, and port mappings.",
        icon: "Network",
      },
    ],
    modules: [
      {
        id: "dmod-1",
        order: 1,
        title: "Getting Started with Containers",
        subtitle: "Why containers matter and core installation.",
        duration: "1h 15m",
        lessons: [
          {
            id: "dles-1-1",
            title: "Introduction to Docker",
            slug: "intro-to-docker",
            duration: "15:00",
            youtubeVideoId: "fqMOX6JJhGo",
            type: "video",
          },
        ],
      },
      {
        id: "dmod-2",
        order: 2,
        title: "Building Docker Images",
        subtitle: "Crafting optimized Dockerfiles.",
        duration: "1h 45m",
        lessons: [
          {
            id: "dles-2-1",
            title: "Writing Your First Dockerfile",
            slug: "first-dockerfile",
            duration: "20:00",
            youtubeVideoId: "gAkwW2tuIqE",
            type: "video",
          },
        ],
      },
    ],
  },
  {
    id: "course-3",
    title: "TypeScript Deep Dive",
    slug: "typescript-deep-dive",
    summary:
      "Go beyond the basics and write safer, more expressive code with advanced type patterns, generics, and compiler options.",
    level: "Intermediate",
    duration: "14h 36m",
    totalModules: 10,
    studentsCount: "3.4k students",
    badge: "Trending",
    badgeVariant: "trending",
    homeBadge: "Trending",
    iconText: "TS",
    iconBg: "bg-blue-600 text-white font-bold",
    coverImageUrl:
      "https://images.unsplash.com/photo-1516116211227-bbc13c6d123c?w=800&auto=format&fit=crop&q=80",
    instructor: {
      name: "Daniel Okafor",
      role: "Staff TypeScript Engineer",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80",
    },
    whatYouLearn: [
      {
        id: "twyl-1",
        title: "Generics & Conditional Types",
        description: "Unlock advanced metaprogramming in TypeScript.",
        icon: "Code",
      },
      {
        id: "twyl-2",
        title: "Template Literal Types",
        description: "Build strongly-typed API route patterns and event emitters.",
        icon: "Sparkles",
      },
      {
        id: "twyl-3",
        title: "Type Narrowing & Guards",
        description: "Safely discriminate unions and assert runtime shapes.",
        icon: "ShieldCheck",
      },
      {
        id: "twyl-4",
        title: "Compiler Configuration",
        description: "Tune tsconfig for optimal performance and strict correctness.",
        icon: "Sliders",
      },
    ],
    modules: [
      {
        id: "tmod-1",
        order: 1,
        title: "TypeScript Core Foundations",
        subtitle: "Type inference, primitives, and structural typing.",
        duration: "1h 30m",
        lessons: [
          {
            id: "tles-1-1",
            title: "Structural vs Nominal Typing",
            slug: "structural-typing",
            duration: "18:00",
            youtubeVideoId: "ahCwqrYpIuM",
            type: "video",
          },
        ],
      },
    ],
  },
];

export const WHY_VIBE_LEARN_FEATURES = [
  {
    id: "f-1",
    title: "Expert-Led Content",
    description: "Learn from industry professionals with real-world experience.",
    icon: "Brain",
  },
  {
    id: "f-2",
    title: "Hands-On Practice",
    description: "Build real projects and apply what you learn immediately.",
    icon: "Zap",
  },
  {
    id: "f-3",
    title: "Structured Learning Paths",
    description: "Follow clear paths from beginner to advanced without guesswork.",
    icon: "GitFork",
  },
  {
    id: "f-4",
    title: "Lifetime Access",
    description: "Learn at your own pace, anytime, anywhere with lifetime updates.",
    icon: "Users",
  },
];
